### PR TITLE
Fix unbound variable

### PR DESCRIPTION
**Pull request by jellonek**
The regression was introduced in #166. Bug is visible only when code is running without a controlling terminal.

### CODE REVIEW

**Comment by ivan4th** [comment]
Thanks!
/approve
/lgtm

**Comment by hoegaarden** [comment]
Note that the `kube_router` tests won't succeed, because `kubectl` uses the wrong / no context. This is an easy fix, I can push that later and you can rebase on that. @ivan4th @jellonek

**Comment by jellonek** [comment]
@hoegaarden thx, rebased.
@ivan4th PTAL again.

**Pull request merged**
