### PR TITLE
Support for IPVS CNI Plugin

### PR DESCRIPTION
**Pull request by pmichali**
Added support for the plugin for IPv4 (does not support IPv6 yet). Can
be used by setting CNI_PLUGIN to "kube-router". As part of the setup,
the kube-proxy daemonset is deleted.

A few warnings occur during up/down, but appear to be benign (e.g.
kube-proxy warns to use a config file, no subnet to delete iptable
rules for IPVS).

Updated the "fixed" version scripts.

Fixes: #158

### CODE REVIEW

**Comment by pmichali** [comment]
@ivan4th Any thoughts on the test_src_master failure. It seems to do kubeadm init and shows a message (doesn't say it is an error) and then gets stuck in a kubeadm reset loop.

```
your configuration file uses an old API spec: "kubeadm.k8s.io/v1alpha1". Please use kubeadm v1.11 instead and run 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
```

It seems like, with V1.11, the API version should be v1alpha2.
Does master need branch need to be updated?

**Comment by rpothier** [comment]
Can we just run kube-proxy in IPVS mode, instead of pulling in kube-router?
i.e. update kubeadm.conf with
kubeProxy:
  config:
    mode: ipvs

**Comment by pmichali** [comment]
@rpothier Never tried that, and it's not listed as a way to setup networking using KubeAdm (whereas using kube-router is listed). Do you know if doing that will provide BGP (which is what kube-router does)? If not, then I'm not sure how it handles routing between nodes.

With kube-router, it uses bride CNI plugin, only for IPAM, and no hairpin or static routes need to be setup. In DinD, the YAML for kube-router sets up the CNI config.

**Comment by pmichali** [comment]
Will give kube-proxy with IPVS to see how that works.

**Comment by pmichali** [comment]
Clarification: Probably should have been clearer on this PR description, but partly it is an issue with the ambiguity of kube-router. Although called a CNI plugin, kube-router is really a networking component, which is really a replacement for kube-proxy, plus more. It has both the advantage of IPVS performance and scale, and the added functionality of BGP for dealing with the routing.

It really is not a CNI plugin, per se, and uses the bridge plugin, with some different settings. For k-d-c, I defined a different CNI_PLUGIN, so that it doesn't do the bridge plugin setup in dindnet script.  Like calico and others, kube-router has a YAML for setup. One thing it does in this YAML, is setup the bridge CNI config file, so functionality in dindnet is not needed (hence the separate CNI_PLUGIN type).

So, I'd like to make this available, as a CNI_PLUGIN "kube-router".  I'm peeking into running kube-proxy in IPVS mode, as @rpothier mentioned, but, if that is another viable method, I'd like to provide that as a separate option for k-d-c, and not as an alternative for kube-router, because kube-router does much more (BGP) and makes the setup even simpler (and works with external BGP,...).

IOW, I'd like to move this PR forward, independent of kube-proxy in IPVS mode.

**Comment by pmichali** [comment]
Talked to @ivan4th and it looks like for master branch Kubernetes, the k-d-c image needs updating. Once that is done, I can rebase this PR to pickup the changes.

**Comment by rpothier** [comment]
@pmichali Sounds good to me.

**Pull request merged**
