### PR TITLE
Allow arbitrary Calico version, default v3.3 

### PR DESCRIPTION
**Pull request by neiljerram**
Specifically, allowing the version to be customized is useful when using
kubeadm-dind-cluster to test our master code, including master
manifests, that hasn't been released yet.  That can be done by setting
CALICO_VERSION=master.

Note:

- From v2.6 to v3.3, we did break the etcd setup out from calico.yaml;
  so Calico v3.3 (and later) with etcd mode needs a separate etcd.yaml
  apply.

- Calico master (post v3.3) doesn't need a separate RBAC manifest.

- Also install calicoctl, so it's ready for use.

### CODE REVIEW

**Comment by neiljerram** [comment]
(Just rebased this on top of @lwr20 's PR at #256 )

**Comment by neiljerram** [comment]
I believe CLA should be good now.

**Comment by neiljerram** [comment]
Maybe now?

**Comment by neiljerram** [comment]
OK, let's try another comment bump to recheck the CLA position...

**Comment by neiljerram** [comment]
Think the CLA may really be fixed now...

**Comment by jellonek** [comment]
Thx. Overall the patch looks good in this form.
/approve

**Pull request merged**
