### PR TITLE
Install CNI_PLUGIN="weave" via cloud.weave.works

### PR DESCRIPTION
**Pull request by brb**
This is the official way to install Weave Net as shown at https://www.weave.works/docs/net/latest/kubernetes/kube-addon/#install.

### CODE REVIEW

**Comment by lukaszo** [comment]
@brb can you rebase? kube-router failures should be fixed in current master

**Comment by brb** [comment]
@lukaszo Rebased.

**Comment by lukaszo** [comment]
It looks like `/retest` doesn't work here. The failed test is not related to the change.

/lgtm

**Pull request merged**
