### PR TITLE
image/rundocker: bind-mount /var/lib/kubelet/pods and /var/logs/pods

### PR DESCRIPTION
**Pull request by AkihiroSuda**
same as #113 but reopened to trigger CircleCI

https://github.com/Mirantis/kubeadm-dind-cluster/pull/113

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Travis failing 
```
+./build/build-local.sh
Sending build context to Docker daemon  44.54kB
Step 1/21 : FROM gcr.io/kubeadm/ci-xenial-systemd:base-master-6f6ae74260bfa1b6d97251e6e0191489aeff0939
manifest for gcr.io/kubeadm/ci-xenial-systemd:base-master-6f6ae74260bfa1b6d97251e6e0191489aeff0939 not found
+cleanup
+[[ -n true ]]
+[[ 1 -ne 0 ]]
+export PATH=/tmp/tmp.4NYj9MFsk7:/home/travis/bin:/home/travis/.local/bin:/opt/pyenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.rvm/gems/ruby-2.4.1/bin:/home/travis/.rvm/gems/ruby-2.4.1@global/bin:/home/travis/.rvm/rubies/ruby-2.4.1/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.7.4.linux.amd64/bin:/usr/local/cmake-3.9.2/bin:/usr/local/clang-5.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.rvm/bin:/opt/pyenv/bin
+PATH=/tmp/tmp.4NYj9MFsk7:/home/travis/bin:/home/travis/.local/bin:/opt/pyenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.rvm/gems/ruby-2.4.1/bin:/home/travis/.rvm/gems/ruby-2.4.1@global/bin:/home/travis/.rvm/rubies/ruby-2.4.1/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.7.4.linux.amd64/bin:/usr/local/cmake-3.9.2/bin:/usr/local/clang-5.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.rvm/bin:/opt/pyenv/bin
+/home/travis/build/Mirantis/kubeadm-dind-cluster/dind-cluster.sh dump64
You need kubectl binary in your PATH to use prebuilt DIND image
```

Also CircleCI was not triggered?

**Comment by AkihiroSuda** [comment]
@ivan4th 

`gcr.io/kubeadm/ci-xenial-systemd` seems removed?

**Comment by ivan4th** [comment]
Thanks for noticing, will fix it shortly.

**Comment by ivan4th** [comment]
Hi, the fix for missing base image is currently in `fix-base-image` branch: https://github.com/kubernetes-sigs/kubeadm-dind-cluster/tree/fix-base-image
I'll merge it to master once I have CI issues sorted out after the repo was moved (CircleCI is not enabled for `kubernetes-sigs` org)

**Comment by AkihiroSuda** [comment]
Thanks for the fix, 

/assign @ivan4th

**Comment by AkihiroSuda** [comment]
travis failed due to flaky network

```
E: Failed to fetch http://mirror.jmu.edu/pub/ubuntu/pool/universe/l/lz4/liblz4-tool_0.0~r114-2ubuntu1_amd64.deb  Unable to connect to mirror.jmu.edu:http:
```

**Comment by AkihiroSuda** [comment]
Kubernetes CI (and CircleCI?) can be only triggered by members now?

**Comment by ivan4th** [comment]
Sorry about the inconvenience, could you please amend and re-push the commit without actually changing anything? CircleCI got detached from this PR during the transition apparently.

**Comment by ivan4th** [comment]
Ok there was another issue with CircleCI settings, so I made a tmp branch to rerun the tests, see it here https://circleci.com/workflow-run/b0e75590-c9f5-4726-862d-f31ecb2f42cb (it's needed just for this test run, so as not to ask you to amend again ...) Let's see if it passes

**Comment by ivan4th** [comment]
Hmm, this PR was also picked up by CircleCI now. ok.

**Comment by ivan4th** [comment]
@AkihiroSuda thanks for the PR! Merging.

**Pull request merged**
