### PR TITLE
Version specific kubeadm.conf files

### PR DESCRIPTION
**Pull request by pmichali**
Changed this to use version specific config files and to use them
based on the kubeadm version, rather than having one template file
and trying to morph it for each version. Foudn that 1.12 is
considerably different config.

The 1.10 template is used for 1.8-1.10, and the 1.13 template is
used for 1.13 and newer versions.

Note: There are new sections and fields for the 1.12 an 1.13 kubeadm.conf
files. For 1.13, the conntack settings were commented out, as I suspect
they are host specific. Other, like the healthz ports, were left there,
even though they are showing IPv4 addresses. This template was generated
from a IPv6 setup, so, at this time, IPv4 is still used for some
things. These may need to be parameterize or removed later, as IPv6
changes are made.

In addition, a problem was seen during kube-router cleanup operations,
causing script to fail with latest kube-router code. Made change to
in-line include a version pinned kube-router config file and call out
that version during cleanup as well.

In future, this could be removed, or the version (and config) could be
updated, as newer kube-router versions are released.

Fixes Issue: #236

### CODE REVIEW

**Comment by pmichali** [comment]
@ivan4th Please take a look. This has per-version config files for kubeadm, and nails kube-router to a specific version.

**Comment by lukaszo** [comment]
@pmichali can you split it into two PRs? One for kubeadm and the second one for kube-router? The second one will unblock other PRs

**Comment by pmichali** [comment]
OK. Created new issue and splitting out the PRs.

**Comment by pmichali** [comment]
@ivan4th @lukaszo rebased to get kube-router fix, and pushed up. Please review.

**Comment by lukaszo** [comment]
I'm not brave enough to merge it without @ivan4th review :) 

/approve

**Comment by pmichali** [comment]
@ivan4th Can you review please?

**Comment by ivan4th** [comment]
Works for me. Thanks!
/approve
/lgtm

**Comment by pmichali** [comment]
Thanks Ivan!

**Pull request merged**
